import { Bebas} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { useLenis } from "@/components/Hooks/useLenis";
import LenisProvider from "@/components/Hooks/lenisProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-full relative`}
      >
        <LenisProvider>
  <Navbar/>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
